backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
local_backend: true
media_folder: 'site/static/uploads'
public_folder: 'uploads'
collections:
  - name: "tables"
    label: "Tables"
    folder: "site/data/tables/"
    extension: "json"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "data"
        name: "data"
        widget: "object"
        fields:
        - {label: "Headers", name: "headers", widget: "list", fields: [{label: "en", name: "en", widget: "string"}, {label: "fr", name: "fr", widget: "string"}]}
        - {label: "Data Row", name: "row", widget: "list", fields: [{label: "cell", name: "cell", widget: "list", field: {label: "value", name: "valeu", widget: "string"}}]}
  - name: "page-en" # Used in routes, e.g., /admin/collections/blog
    label: "EN Page" # Used in the UI
    folder: "site/content/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter: {field: "language", value: "en"}
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md" # Filename template, e.g., YYYY-MM-DD-title.md
    path: "{{section}}/{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr"]}
      - {label: "Section", name: "section", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Table", name: "table", widget: "relation", collection: "tables", searchFields: ["title"], displayFields: ["title"], valueField: "data"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page-fr" # Used in routes, e.g., /admin/collections/blog
    label: "FR Page" # Used in the UI
    folder: "site/content/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter: {field: "language", value: "fr"}
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.fr.md" # Filename template, e.g., YYYY-MM-DD-title.md
    path: "{{section}}/{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Language", name: "language", widget: "select", options: ["en", "fr"]}
      - {label: "Section", name: "section", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
